# Generated by Django 3.0.4 on 2020-03-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(max_length=120, unique=True, verbose_name=models.CharField(max_length=120)),
        ),
    ]
