# Generated by Django 3.0.4 on 2020-03-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200330_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
